run:
  go: 1.21
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - asciicheck
    - dupl
    - errname
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - godot
    - godox
    - goerr113
    - gofumpt
    - gomnd
    - lll
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - revive
    - tagliatelle
    - tagalign
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - thelper
    - gci
    # deprecated linters
    - depguard
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - ireturn
    - varcheck

linters-settings:
  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict

  cyclop:
    max-complexity: 15 # the default of 10 was unnecessarily strict

issues:
  exclude-rules:
    # we need to reference a deprecated field in order to trace possible usage
    - path: logger.go
      linters:
        - zerologlint
