#
# Running locally:
#   docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.46.1 golangci-lint run -v
#

run:
  go: 1.18

linters:
  enable-all: true
  disable:
  - exhaustruct # issues introduced by latest golangci-lint:v1.46.1, fix this in a separate PR
  - gofumpt
  - gochecknoglobals
  - wrapcheck
  - varnamelen
  - tagliatelle
  - testpackage
  - paralleltest
  - gomnd
  - goerr113
  - dupl
  - forbidigo
  - funlen
  - unparam
  - wsl
  - errname
  - exhaustivestruct
  - nilnil
  - nlreturn
  - goconst
  - lll
  - asciicheck
  - gocognit
  - godot
  - godox
  - nestif
  - prealloc
  - revive
  # deprecated linters
  - interfacer
  - golint
  - scopelint
  - maligned

linters-settings:
  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict

issues:
  exclude-rules:
    # issues introduced by latest golangci-lint:v1.46.1, fix this in a separate PR
    - path: config.go
      linters:
        - nonamedreturns
