run:
  go: 1.21
  timeout: 5m
  tests: false
  skip-dirs:
    - kafkatest

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    #    - containedctx
    #    - contextcheck
    #    - cyclop
    - decorder
    #    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    #    - exhaustive
    #    - exhaustruct
    - exportloopref
    #    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    #    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    #    - godox
    #    - goerr113
    - gofmt
    #    - gofumpt
    - goheader
    #    - goimports
    #    - gomnd
    #    - gomoddirectives
    - gomodguard
    - goprintffuncname
    #    - gosec # disable as we run gosec as an explicit step
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    #    - ireturn
    #    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    #    - nakedret
    - nestif
    - nilerr
    #    - nilnil
    #    - nlreturn
    - noctx
    - nolintlint
    #    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    #    - revive
    - rowserrcheck
    - sqlclosecheck
    #    - staticcheck
    #    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    #    - varnamelen
    - wastedassign
    - whitespace
    #    - wrapcheck
    #    - wsl
    - zerologlint

linters-settings:
  funlen:
    lines: 120
    statements: 50

  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(gopkg.in) # Custom section: groups all imports with the specified Prefix.
      - prefix(github.com)
      - prefix(goa.design)
    #  - blank                          # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
    #  - dot                            # Dot section: contains all dot imports. This section is not present unless explicitly enabled.

    # Skip generated files.
    # Default: true
    #skip-generated: false

    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    #custom-order: true

  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict

  cyclop:
    max-complexity: 15 # the default of 10 was unnecessarily strict

issues:
  exclude-rules:

    # too hard to refactor
    - path: x/log/helper.go
      linters:
        - nestif

    # []string hard to initialize prealloc with default value
    - path: x/vault/vault_decrypter.go
      linters:
        - prealloc

    # []string hard to initialize prealloc with default value
    - path: x/vault/vault_encrypter.go
      linters:
        - prealloc

    # too hard to refactor
    - path: x/kafka/consumer/consumer.go
      linters:
        - nestif

    # we need to reference a deprecated field in order to trace possible usage
    - path: log/logger.go
      linters:
        - zerologlint

    - path: log/helper.go
      linters:
        - nestif

    - path: log/strings.go
      linters:
        - nestif

    - path: env/settings.go
      linters:
        - tagliatelle
