name: pipeline
on:
  push:
    branches:
      - main

  pull_request:

env:
  GO_VERSION: 1.21

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Tidy dependencies
        run: go mod tidy

      - name: Install dependencies
        run: go get .

      - name: Build
        run: GOARCH=amd64 GOOS=linux go build ./...

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: ./src/go.sum

      - name: GOLangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: --verbose --timeout=5m
          skip-pkg-cache: true

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: ./src/go.sum

      - name: Test code
        run: |
          make test-ci

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: artifacts/count.out
