name: pipeline
on:
  push:
    branches:
      - main

  pull_request:

env:
  GO_VERSION: 1.21

jobs:
  go-ensure-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Check Go Modules
        run: make ensure-deps

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: ./go.sum

      - name: Build
        run: GOARCH=amd64 GOOS=linux go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: "-v --verbose --timeout=5m"
          skip-pkg-cache: true

  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: ./go.sum

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test code
        run: |
          make test-ci

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: artifacts/count.out
