name: pipeline
on:
  push:
    branches:
      - main

  pull_request:

env:
  GO_VERSION: 1.21
  GOTOOLCHAIN: go1.21.6

jobs:
  go-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./go.sum
          check-latest: true

      - name: Tidy dependencies
        run: go mod tidy

  go-lint:
    needs: [go-setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./go.sum

      - name: GoLint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: --verbose --timeout=5m
          skip-pkg-cache: true

      - name: GoVet
        run: go vet ./...

  # this takes a long time to run, so we continue with go-build, go-test etc. in parallel
  # should we exclude /x/... to speed up this steps?
  go-sec:
    needs: [go-setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./go.sum

      - name: GoSec
        uses: securego/gosec@master
        with:
          args: ./...

  go-build:
    needs: [go-setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./go.sum

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: GOARCH=amd64 GOOS=linux go build ./...

  go-test:
    needs: [go-lint, go-build, go-sec]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./go.sum

      - name: Test code
        run: |
          make test-ci

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: artifacts/count.out
