name: Release on merge to main
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  add-git-patch-tag-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create version tag for main
        uses: anothrNick/github-tag-action@1.67.0
        env: # https://github.com/anothrNick/github-tag-action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main